version: "3.9"

services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=secretpassword
    volumes:
      - couchdb_data:/opt/couchdb/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO Console port
    volumes:
      - minio_data:/data  # Persistent storage for MinIO data
    environment:
      MINIO_ROOT_USER: minioadmin  # Root user for MinIO Console
      MINIO_ROOT_PASSWORD: minioadmin  # Root password for MinIO Console

    command: server --console-address ":9001" /data

volumes:
  couchdb_data:
  minio_data:
