version: "3.9"

services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=secretpassword
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
